jobs:
    - job: TerraformDestroy
      displayName: Terraform Destroy
      steps:
          - task: TerraformInstaller@0
            displayName: Terraform Install
            inputs:
              terraformVersion: '${{parameters.terraform_version}}'
          - task: TerraformTaskV3@3
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: '${{parameters.backendServiceArm}}'
              backendAzureRmResourceGroupName: '${{parameters.backendAzureRmResourceGroupName}}'
              backendAzureRmStorageAccountName: '${{parameters.backendAzureRmStorageAccountName}}'
              backendAzureRmContainerName: '${{parameters.backendAzureRmContainerName}}'
              backendAzureRmKey: '${{parameters.backendAzureRmKey}}'
          - task: TerraformTaskV3@3
            displayName: Terraform Destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              commandOptions: '-auto-approve -var-file="../${{parameters.environment}}/${{parameters.environment}}.tfvars"'
              environmentServiceNameAzureRM: '${{parameters.backendServiceArm}}'