jobs:
    - job: TerraformPlan
      displayName: Terraform Plan
      steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '${{parameters.terraform_version}}'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendAzureRmResourceGroupName: '${{parameters.backendAzureRmResourceGroupName}}'
              backendAzureRmStorageAccountName: '${{parameters.backendAzureRmStorageAccountName}}'
              backendAzureRmContainerName: '{{parameters.backendAzureRmContainerName}}'
              backendAzureRmKey: '${{parameters.backendAzureRmKey}}'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'