#trigger: none

jobs:
    - job: TerraformPlan
      displayName: Terraform Plan
      continueOnError: false
      steps:
          - task: TerraformInstaller@0
            displayName: Terraform Install
            inputs:
              terraformVersion: '${{parameters.terraform_version}}'
          - task: TerraformTaskV3@3
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: '${{parameters.backendServiceArm}}'
              backendAzureRmResourceGroupName: '${{parameters.backendAzureRmResourceGroupName}}'
              backendAzureRmStorageAccountName: '${{parameters.backendAzureRmStorageAccountName}}'
              backendAzureRmContainerName: '{{parameters.backendAzureRmContainerName}}'
              backendAzureRmKey: '${{parameters.backendAzureRmKey}}'
          - task: TerraformTaskV3@3
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: '${{parameters.backendServiceArm}}'
              #commandOptions: '-var-file="../${{parameters.environment}}/${{parameters.environment}}.tfvars"'