#trigger: none

jobs:
    - job: TerraformApply
      displayName: Terraform Apply
      steps:
          - task: TerraformInstaller@0
            displayName: Rerraform Install
            inputs:
              terraformVersion: '${{parameters.terraform_version}}'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: '${{parameters.backendServiceArm}}'
              backendAzureRmResourceGroupName: '${{parameters.backendAzureRmResourceGroupName}}'
              backendAzureRmStorageAccountName: '${{parameters.backendAzureRmStorageAccountName}}'
              backendAzureRmContainerName: '${{parameters.backendAzureRmContainerName}}'
              backendAzureRmKey: '${{parameters.backendAzureRmKey}}'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: '${{parameters.backendServiceArm}}'
              #commandOptions: '-var-file="../${{parameters.environment}}/${{parameters.environment}}.tfvars"'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: '${{parameters.backendServiceArm}}'
              #commandOptions: '-var-file="../${{parameters.environment}}/${{parameters.environment}}.tfvars"'