trigger: none

stages:
    - stage: TerraformValidate
      displayName: Terraform Validate
      jobs:
          - template: templates/terraform-validate.yaml
            parameters:
                backendServiceArm: ${{variables.backendServiceArm}}
                terraform_version: ${{variables.terraform_version}}
                backendAzureRmResourceGroupName: ${{variables.backendAzureRmResourceGroupName}}
                backendAzureRmStorageAccountName: ${{variables.backendAzureRmStorageAccountName}}
                backendAzureRmContainerName: ${{variables.backendAzureRmContainerName}}
                backendAzureRmKey: ${{variables.backendAzureRmKey}}

    - stage: TerraformPlan
      displayName: Terraform Plan
      dependsOn: [TerraformValidate]
      condition: succeeded('TerraformValidate')
      jobs:
        - template: templates/terraform-plan.yml
          parameters:
                backendServiceArm: ${{variables.backendServiceArm}}
                terraform_version: ${{variables.terraform_version}}
                backendAzureRmResourceGroupName: ${{variables.backendAzureRmResourceGroupName}}
                backendAzureRmStorageAccountName: ${{variables.backendAzureRmStorageAccountName}}
                backendAzureRmContainerName: ${{variables.backendAzureRmContainerName}}
                backendAzureRmKey: ${{variables.backendAzureRmKey}}
                environment: ${{variables.environment}}
    
    - stage: TerraformApply
      displayName: Terraform Apply
      condition: succeeded('TerraformPlan')
      dependsOn: [TerraformPlan]
      jobs:
        - template: templates/terraform-apply.yaml
          parameters:
                backendServiceArm: ${{variables.backendServiceArm}}
                terraform_version: ${{variables.terraform_version}}
                backendAzureRmResourceGroupName: ${{variables.backendAzureRmResourceGroupName}}
                backendAzureRmStorageAccountName: ${{variables.backendAzureRmStorageAccountName}}
                backendAzureRmContainerName: ${{variables.backendAzureRmContainerName}}
                backendAzureRmKey: ${{variables.backendAzureRmKey}}
                environment: ${{variables.environment}}
